version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: test
    ports:
      - "5432:5432"

  app:
    build: .
    command: yarn start
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app